# @format

# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed

# jobs:
# build:
#        runs-on: [aws-ec2]

#     deploy:
#     needs: build
#     runs-on: [aws-self-hosted]
#     steps:
#       - name: Pull image from docker hub
#         run: docker pull rohitprajapat8875/nodejs-app:latest
#       - name: Delete old container
#         run: docker rm -f nodejs-app-container
#       - name: Run docker container
#         run: docker run -d -p 5000:5000 --name nodejs-app-container rohitprajapat8875/nodejs-app
