# @format

name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Build docker image
        run: docker build -t rohitprajapat8875/nodejs-app:${{ steps.commit_hash.outputs.hash }} .
      - name: Publish image to docker hub
        run: docker push rohitprajapat8875/nodejs-app:{{ steps.commit_hash.outputs.hash }}
  # deploy:
  #   needs: build
  #   runs-on: [aws-ec2]
  #   steps:
  #     - name: Pull image from docker hub
  #       run: sudo docker pull rohitprajapat8875/nodejs-app:latest
  #     - name: Delete old container
  #       run: sudo docker rm -f nodejs-app-container
  #     - name: Run docker container
  #       run: sudo docker run -d -p 5000:5000 --name nodejs-app-container rohitprajapat8875/nodejs-app

  ########################## For Another CD.yml ####################

  # @format
# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed

# jobs:
# build:
#        runs-on: [aws-ec2]

#     deploy:
#     needs: build
#     runs-on: [aws-self-hosted]
#     steps:
#       - name: Pull image from docker hub
#         run: docker pull rohitprajapat8875/nodejs-app:latest
#       - name: Delete old container
#         run: docker rm -f nodejs-app-container
#       - name: Run docker container
#         run: docker run -d -p 5000:5000 --name nodejs-app-container rohitprajapat8875/nodejs-app
